services:
  - type: web
    name: whatsapp-server
    env: image
    plan: free
    image:
      url: evoapicloud/evolution-api:lite
    envVars:
      - key: PORT
        value: 8080
      - key: AUTHENTICATION_API_KEY
        value: MaCleSecrete2024
      - key: WEBHOOK_URL
        value: https://whatsapp-server.onrender.com
